apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        # Nível 3: Link Técnico (Trace ID gerado pelo OpenTelemetry)
        - datasourceUid: tempo
          matcherRegex: '"traceId":\s*"([a-f0-9]{32})"'
          name: "🔍 Debug: View Technical Trace"
          url: "$${__value.raw}"
          internalLinkEnabled: true
        
        # Nível 3: Link de Negócio (Correlation ID do Payload)
        - datasourceUid: tempo
          matcherRegex: '"correlationId":\s*"([^"]+)"'
          name: "💼 Support: Search Business Flow"
          url: '{ .messaging.correlation_id = "$${__value.raw}" }'
          internalLinkEnabled: true
