apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: admin
    secureJsonData:
      password: passw123
    jsonData:
      database: messages_db
      sslmode: disable
